name: Update weekly item

on:
  push:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Run script
      run: |
        python3 update-readme.py
        git add .
        git config user.name github-actions
        git config user.email ruthetum@gmail.com
        git commit -am "Update weekly item"
        git push
